export const FETCH_SEARCH_PENDING = "FETCH_SEARCH_PENDING";
export const FETCH_SEARCH_FAILURE = "FETCH_SEARCH_FAILURE";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";

export default [
    FETCH_SEARCH_PENDING,
    FETCH_SEARCH_FAILURE,
    FETCH_SEARCH_SUCCESS,
]