export const FETCH_USER_PENDING = "FETCH_USER_PENDING";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_UPDATE = "FETCH_USER_UPDATE";

export default [
    FETCH_USER_PENDING,
    FETCH_USER_FAILURE,
    FETCH_USER_SUCCESS,
    FETCH_USER_UPDATE,
];
